repos:
  - repo: local
    hooks:
      - id: jupyter-nbconvert
        name: jupyter-nbconvert
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --to markdown
